/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/wardrobe-8.glb --t 
Author: DKDTheGreat1 (https://sketchfab.com/DKDTheGreat1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wardrobe-low-poly-adae92e3e6ed4302adaf37f96ca925ba
Title: Wardrobe (Low poly)
*/

import * as THREE from 'three'
import React, { useContext, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { DimensionContext } from '../contexts/DimensionContext'
import { MaterialContext } from '../contexts/MaterialContext'
import { useLoader } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
  }
  materials: {
    Main: THREE.MeshStandardMaterial
    silver: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Wardrobe8(props: JSX.IntrinsicElements['group']) {
 const {dimensions} = useContext(DimensionContext)
 const {material} = useContext(MaterialContext)
  const { nodes, materials } = useGLTF('/wardrobe-8.glb') as GLTFResult
  // console.log(materials.Main)
  const bodymap = useLoader(THREE.TextureLoader,material.body.src)
  const doormap = useLoader(THREE.TextureLoader,material.door.src)
  const {x,y,z} = dimensions
  return (
    <group {...props} dispose={null}>
      <mesh 
       name="main-body" 
       geometry={nodes.Object_4.geometry} 
       scale={[
        x ,
        y ,
        z 
       ]} >
        <meshStandardMaterial
         map={bodymap}
        />
      </mesh>
      <mesh 
       name="leftdoor" scale={[
       (x/2) ,
        y ,
        z 
       ]} 
        position={[-x/2.8,0,0]} rotation={[0,0,0]} geometry={nodes.Object_6.geometry}>
        <meshStandardMaterial
        map={doormap}
        />  
        </mesh>  
      <mesh 
       name="rightdoor" scale={[
        (x/2) ,
        y ,
        z 
       ]} 
        position={[x/2.8,0,0]} rotation={[0,0,0]} geometry={nodes.Object_6.geometry}  material={materials.Main} >
          <meshStandardMaterial
          map={doormap}
         /> 
        </mesh>
     
      <mesh name="handle-1" scale={[x,y,z]} geometry={nodes.Object_8.geometry} material={materials.silver} />
      <mesh name="handle-2" scale={[x,y,z]} geometry={nodes.Object_10.geometry} material={materials.silver} />
      <mesh name="stand-1" scale={[x,y,z]}  geometry={nodes.Object_12.geometry} material={materials.silver} />
      <mesh name="stand-2" scale={[x,y,z]} geometry={nodes.Object_14.geometry} material={materials.silver} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.silver} />
    </group>
  )
}

useGLTF.preload('/wardrobe-8.glb')
