/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/book_shelf.glb --t 
Author: Pixel-bit (https://sketchfab.com/Pixel-bit)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bookshelf-household-props-challenge-day-12-5971be37036848c6aa745ee41f4802bb
Title: Bookshelf - Household Props Challenge - Day 12
*/

import * as THREE from 'three'
import React, { useContext, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useLoader } from '@react-three/fiber'
import {DimensionContext} from '../../contexts/DimensionContext'
import {MaterialContext} from '../../contexts/MaterialContext'

type GLTFResult = GLTF & {
  nodes: {
    pCube3_lambert1_0: THREE.Mesh
  }
  materials: {
    lambert1: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function BookShelf(props: JSX.IntrinsicElements['group']) {
  const {material} = useContext(MaterialContext)
  const {dimensions} = useContext(DimensionContext)
  const bodyMap = useLoader(THREE.TextureLoader,material.body.src)
  const BodyMaterial = new  THREE.MeshStandardMaterial()
  BodyMaterial.map = bodyMap
  const {x,y,z} = dimensions
  const { nodes, } = useGLTF('/book_shelf.glb') as GLTFResult

  return (
    <group {...props} scale={[z*2,y,x]} dispose={null}>
      <mesh geometry={nodes.pCube3_lambert1_0.geometry} material={BodyMaterial} />
    </group>
  )
}

useGLTF.preload('/book_shelf.glb')
